### ISSUE TITLE
pacaur stuck on resolving dependencies

### ISSUE THREAD

**Issue by Binero** [rmarquis/pacaur#347] opened 2015-07-16 11:51 UTC
I am trying to install `libx32-readline` from the AUR. (Don't judge.) When I try to `pacaur -S libx32-readline` it never stops resolving dependencies. When trying to install with makepkg (`makepkg -si`) it does successfully fail to find dependencies.

**Comment by rmarquis** [comment] 2015-07-16 13:03
This issue happens because an obsolete dependency (gcc-libs-multilib-x32) that explicitly requires an unavailable old version. As AUR versioning check was implemented a few months ago (see #314), the solver correctly doesn't find the dependency in AUR but it still tries to find it in AUR for some reason.

The cyclic dependency check needs to be improved here.

**Comment by rmarquis** [comment] 2015-07-16 18:26
Having had a closer look, my initial assumption is wrong. The issue isn't due to an obsolete AUR package, but is due to a dependency cycle produced by the 'good' packages:

* ```libx32-glibc``` requires ```gcc-multilib-x32``` as makedep, which in turns requires ```libx32-glibc``` as makedep.
* ```gcc-libs-multilib-x32``` requires ```libx32-glibc``` ... which eventually requires ```libx32-glibc``` (see above)

I guess it is time to implement #285.

**Comment by rmarquis** [comment] 2015-07-16 20:03
Fixed in #285, closing.

**Closed by rmarquis** 2015-07-16 20:03 UTC
Labels: bug
