### ISSUE TITLE
.SRCINFO mismatch when installing exfat-dkms-git

### ISSUE THREAD

**Issue by freswa** [rmarquis/pacaur#419] opened 2016-02-11 14:15 UTC
When trying to install the pkg exfat-dkms-git via pacaur it reports
```
:: exfat-dkms-git package(s) failed to install. Check .SRCINFO for mismatching data with PKGBUILD.
```
while the SRCINFO seems to match perfectly.
This seems not to be related to #409 - PKGEXT is not defined...

**Comment by freswa** [comment] 2016-02-11 14:24
Just found the issue by debugging. The issue was a whitespace in the pkgrel which leads to this
```
+ GetBuiltPkg 'exfat-dkms-git-158.7f71834-1 ' /tmp/pacaurtmp-user/exfat-dkms-git
+ builtpkg='/tmp/pacaurtmp-user/exfat-dkms-git/exfat-dkms-git-158.7f71834-1 -x86_64.pkg.tar'
+ [[ ! -f /tmp/pacaurtmp-user/exfat-dkms-git/exfat-dkms-git-158.7f71834-1 -x86_64.pkg.tar ]]
+ builtpkg='/tmp/pacaurtmp-user/exfat-dkms-git/exfat-dkms-git-158.7f71834-1 -any.pkg.tar'
+ [[ ! -f /tmp/pacaurtmp-user/exfat-dkms-git/exfat-dkms-git-158.7f71834-1 -any.pkg.tar ]]
+ builtpkg='/tmp/pacaurtmp-user/exfat-dkms-git/exfat-dkms-git-158.7f71834-1 -x86_64.pkg.tar'
+ [[ ! -f /tmp/pacaurtmp-user/exfat-dkms-git/exfat-dkms-git-158.7f71834-1 -x86_64.pkg.tar ]]
+ builtpkg='/tmp/pacaurtmp-user/exfat-dkms-git/exfat-dkms-git-158.7f71834-1 -any.pkg.tar'
+ [[ ! -f /tmp/pacaurtmp-user/exfat-dkms-git/exfat-dkms-git-158.7f71834-1 -any.pkg.tar ]]
+ unset builtpkg
+ [[    =~  exfat-dkms-git  ]]
+ builtpkgs+=($builtpkg)
+ [[ -n true ]]
```
I think this is a bug.

**Comment by rmarquis** [comment] 2016-02-11 14:26
The `exfat-dkms-git` package has just been updated a few minutes ago. Does the issue still happen?

**Comment by freswa** [comment] 2016-02-11 14:27
No the issue has been fixed by removing the whitespace upstream (by me).

**Comment by rmarquis** [comment] 2016-02-11 14:29
The package name is generated by makpekg, while pacaur tries to retrieve the exact version match with the infor provided by the .SRCINFO file (which seems to be unaffected by that white space). I cannot "fix" that in pacaur, but this might be worth a bug report to the pacman/makepkg devs.

**Comment by freswa** [comment] 2016-02-11 14:31
Thanks!

**Comment by rmarquis** [comment] 2016-02-11 14:38
Hmm, I might have spoken too soon. This might be an issue with pacaur but only happening when installing -git packages. I'll have a closer look tonight. Thanks for the report.

**Comment by freswa** [comment] 2016-02-11 14:45
Git bisect gives me this commit:
```
6b2c1ed9726538434cfae0865c637579be430765 is the first bad commit
commit 6b2c1ed9726538434cfae0865c637579be430765
Author: Remy Marquis <remy.marquis@gmail.com>
Date:   Tue Oct 27 14:57:42 2015 +0100

    use pacman -U for installation

:100755 100755 10814542568f649de9f6e674fc9e525403a01a96 7a3f2d125ef3b7665baebd27653efeff58820a8f M	pacaur
```

**Comment by rmarquis** [comment] 2016-02-11 14:57
Thanks. There are quite a few regressions due to pacman 5.0 and the removal of the `--pkg` flag. I had to change the way packages are installed, by using `pacman -U` instead of using `makepkg -i` to ensure split packages correctly install.

Here the pkgver grep call to the PKGBUILD should be sanitized. Note pacaur usually doesn't parse PKGBULDs, as the info provided the the .SRCINFO is equivalent (through the RPC interface). This is done solely here because it is the only place where the updated pkgver is available when installing -git packages.

Fix is trivial, I'll do a new release tonight.

**Comment by rmarquis** [comment] 2016-02-11 20:11
Fixed in 6c3aa86b87932c1be11b72d820dce4637b8777f9.

**Closed by rmarquis** 2016-02-11 20:11 UTC
Labels: bug

**Comment by aminb** [comment] 2016-06-20 02:26
@rmarquis I get a similar error when trying to install `mba6x_bl-dkms` from aur:

```
:: mba6x_bl-dkms package(s) failed to install. Check .SRCINFO for mismatching data with PKGBUILD.
```

And here's me trying to figure out what's wrong:

```
λ cd .cache/pacaur/mba6x_bl-dkms/

~/.cache/pacaur/mba6x_bl-dkms master*
λ makepkg --printsrcinfo > .SRCINFO-new

~/.cache/pacaur/mba6x_bl-dkms master*
λ diff .SRCINFO .SRCINFO-new 
1,2d0
< # Generated by mksrcinfo v8
< # Wed Mar 30 05:18:05 UTC 2016
5c3
< 	pkgver = latest
---
> 	pkgver = 47.d05c125
```

**Comment by rmarquis** [comment] 2016-06-20 07:59
Please follow proper VCS guidelines.

**Comment by aminb** [comment] 2016-06-22 15:33
I'm not the packager, but thanks I'll report it on the package page so the maintainer can check for problems.
