### ISSUE TITLE
Installing cached packages pulls in build dependencies

### ISSUE THREAD

**Issue by olantwin** [rmarquis/pacaur#326] opened 2015-04-17 08:28 UTC
Preparation: PKGDEST set and used to cache built packages.
Pacaur version: 4.2.24.1.g3e56022 and 4.2.24

Steps to reproduce:
1. `pacaur -m <package>` (or manually build and delete build dependencies using `makepkg` and `pacman`)
Package is built, build dependencies are automatically uninstalled. Build without incident.
2. `pacaur -S <package>`
Cached package is found and offered for installation, along with build dependencies. (Expected result: Package is installed, installing run-time dependencies if applicable and ignoring build dependencies).

I can reproduce this with [`corebird`](https://aur.archlinux.org/packages/corebird/) and [`california`](https://aur.archlinux.org/packages/california/) packages, but those are all I tried for now. 

`bash -x pacaur -S <package>`:
[corebird](https://gist.github.com/olantwin/810826e8c7fb154dfde3)
[california](https://gist.github.com/olantwin/df9ae7960171c92d49ed)

Apologies if this is a known issue, I could not find it reported elsewhere.
If you need any more information (assuming this is not intended behaviour), I'm happy to help.

**Comment by rmarquis** [comment] 2015-04-17 09:14
Thanks for the detailed report - this is much appreciated.

This seems indeed to be a bug, but only in the main prompt display. The build dependencies aren't installed again by pacman. This happens because pacaur computes the dependency list by itself - and wrongly adds makedeps here - but it lets makepkg handle the binary dependencies installation.

**Comment by olantwin** [comment] 2015-04-17 09:20
Thanks for the quick reply. 

Indeed, the bug is purely cosmetic. Did not think about actually going through with the proposed changes to check whether the build dependencies were actually installed. It seems I trust `pacaur` too much ;).

**Comment by rmarquis** [comment] 2015-04-17 11:07
Fixed in 1f520e625647f30600acd680e3ea89f98e98a704.

**Comment by rmarquis** [comment] 2016-08-19 11:02
The individual cache check for AUR makedeps/checkdeps that was implemented in #535 (651d62e52371f3ad8893e5c28b18ec3597eb7754) has been removed with 2b79323bd3ddbaa6eb3712fe5bfb1fc133187fc5 to avoid a nasty issue.

It should be reimplemented though. I'm reopening this ticket for tracking this minor bug fix.

**Comment by rmarquis** [comment] 2016-08-19 19:58
Actually, this issue fixed itself while fixing #535. The makedeps/checkdeps will only appear in the prompt if the parent package needs to be built, and if cached (but not installed) will appear in prompt. They don't appear if already installed, which is the expected behavior.

**Closed by rmarquis** 2016-08-19 19:58 UTC
Labels: bug
