### ISSUE TITLE
support alternative installation root

### ISSUE THREAD

**Issue by mylese** [rmarquis/pacaur#338] opened 2015-06-21 21:28 UTC
The manpage says this is not supported.  I am wondering if it might be worth another look given the success of systemd-nspawn.

[clean-chroot-manager](https://github.com/graysky2/clean-chroot-manager) (ccm), says it is *"wrapper script[s] to manage clean chroots...for building packages under Arch Linux."*  It wraps some of operations described in [the wiki: Building_in_a_Clean_Chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot) and additionally does basic management of a local repository within the systemd-nspawn (chroot).  To build and install a package in the clean chroot I have to cd into the directory on the host containing the PKGBUILD and source before running "sudo ccm i".

It would be nice if I could ask pacaur to install lots of little dependencies from AUR into the chroot without having to set up the directories, download the sources, build etc.

The dependencies for ccm are something like: ```ccm -> (pacstrap, mkarchroot, makechrootpkg) -> arch-nspawn -> systemd-nspawn``` In particular, [makechrootpkg](https://github.com/falconindy/devtools/blob/master/makechrootpkg.in), part of the devtools package, looks as if it could be very useful to pacaur to achieve this.

**Comment by mylese** [comment] 2015-06-21 21:47
One way to conveniently install *"lots of little dependencies from AUR"* might be to build them on the main host and then add them to a custom local repo that clean-chroot-manager then makes available to the chroot.  I haven't fully thought this through though.  Pacaur supporting an alternative root would be easier (for me).

**Comment by rmarquis** [comment] 2015-06-21 23:24
I am not using that feature and won't invest time in this feature, but patches are welcome.

The first issue is that the -r command line option is reserved for restricting to repositories, but AFAIK there are also a few incompatibilities here and there and some adjustment might be needed.

**Comment by rmarquis** [comment] 2015-08-17 09:11
Done in 870418d1c6baf3905a143267edd8a3efafffadd1. Only the long ```--root``` option is taken into account, the short ```-r``` option is reserved.

**Comment by mylese** [comment] 2015-08-17 11:07
Thankyou very much it is really appreciated, I will try it out as soon as I can.

**Comment by rmarquis** [comment] 2015-08-17 11:44
Note I'm not 100% sure if this actually does what you need, so feedback welcome. Feel free to reopen/comment if the need arise.

**Comment by jonhoo** [comment] 2015-08-25 11:52
While this works for commands that only run `pacman`, it does *not* work for packages that are built (and installed) using `makepkg` (i.e. everything from the AUR). Unfortunately, `makepkg` doesn't have a `--root` equivalent either, so the only way of doing it as far as I can tell is to *just* build with `makepkg`, and then install with `pacman -U ${pacopts[@]}` (which will also use `--root` correctly) separately.

**Comment by rmarquis** [comment] 2015-08-25 12:12
Using ```pacman -U```has too many drawbacks regarding split package support. This is a way I'm not going in.

**Comment by jonhoo** [comment] 2015-08-25 12:13
That's a shame. It effectively makes support `--root` useless, as it can't be used with package installation at all :/

**Comment by rmarquis** [comment] 2015-08-25 18:47
If the issue is that makepkg can't build as root, this is a different issue - one that I won't try to workaround.

**Comment by jonhoo** [comment] 2015-08-25 20:21
No, the issue is that makepkg can't *install into* a root (like `pacman` can with the `--root` flag). This is purely a package installation issue I think, and not a package building issue.

**Comment by rmarquis** [comment] 2015-08-25 20:26
I see, I confused the old ```--asroot``` flag of makepkg with this ```--root``` flag. Might be worth requesting support for that flag upstream, if your user case makes sense when used with makepkg alone.

**Comment by jonhoo** [comment] 2015-08-25 21:54
Filed upstream at https://bugs.archlinux.org/task/46108

**Comment by rmarquis** [comment] 2015-08-25 22:08
Thank you! I subscribed to the notification list.

**Comment by mylese** [comment] 2015-08-26 09:30
jonhoo, you want to build a package outside a chroot then install the package in a chroot? I want to build a package in a chroot and also install it there.  The package has many dependencies that are also in the AUR.  I could do it like this:
- download source for dependency1
- build in chroot using makechrootpkg
- add package to local repo using repo-add (or [repoze](https://github.com/vodik/repose))
- repeat for dependent package and pacman will find dependency1 package in the local repo

I had thought that pacaur could be modified to download, build, install for each dependency in a single chroot but now I think that it would have to repeat the whole setup each time the main package was rebuilt.  I think that the method using a local repo is better.  Not sure where the repo should be: on the main system, or in the clean chroot. Clean-chroot-manager (see my first post) could help with that.  Pacaur is very good at what it does and repo management and chroots may be too OT.  Having said that, perhaps the first two steps would be possible if pacaur called makechrootpkg instead of makepkg.  Adds a dependency to devtools though.  Time to get my Bash out.

**Comment by rmarquis** [comment] 2015-08-26 11:32
```makechroot``` seems indeed to be able to install in a chroot:

```
makechrootpkg -r $CHROOT -- -i
```

It is possible to add a variable for makepkg in pacaur, similarly to what is done with ```$PACMAN```. Would this be of any help?

**Comment by mylese** [comment] 2015-08-26 21:30
Good idea, looks like it could work when called like this:
```$  MAKEPKG="makechrootpkg -r mychroot --" pacaur -S mypackage```

**Comment by rmarquis** [comment] 2015-09-09 10:40
Came across this project: https://github.com/PaulAvery/archci
I see it builds with ```pacaur -m``` then install with ```pacman -r```. Maybe this is also applicable to your user case.

**Comment by jonhoo** [comment] 2015-09-09 15:13
Yeah, that's the same thing I currently do in https://github.com/jonhoo/cloud-arch too (combined with `--foreign`).

**Comment by rmarquis** [comment] 2015-09-10 11:06
Is there still a need to make it work with pacaur? Since this feature is out-of-scope of the initial objectives, I'd rather close this feature is some easy workaround can be used instead.

**Comment by jonhoo** [comment] 2015-09-10 23:00
Meh, I think the workaround of building with pacaur and then installing with pacman actually works fine.

**Closed** 2015-09-11 22:55 UTC
Labels: feature, wontfix

**Comment by rmarquis** [comment] 2015-10-27 20:27
@mylese @jonhoo FYI, future versions of pacaur will use ```pacman -U```, if that could be of any help. This is already implemented in the _pacaur44_ branch although it is barely tested as of now.

To make it short, the next makepkg will remove the ```--pkg``` flag (see #364), so I have to fallback on ```pacman -U``` to handle split packages installation. Hopefully, there will be no regression with split packages, but I certainly wouldn't bet on it.

**Comment by jonhoo** [comment] 2015-10-27 21:11
Oh, that might help significantly. Then we can just pass `--root` as a pacman flag, and it should solve the problem.
