### ISSUE TITLE
Anaconda Python distribution breaks AUR lookup

### ISSUE THREAD

**Issue by chendaniely** [rmarquis/pacaur#345] opened 2015-07-16 00:07 UTC
The [Anaconda](http://www.continuum.io/) Python distribution adds a line to the `.bashrc` file that (by default) prepends the following path to the `$PATH`:

    # added by Anaconda3 2.3.0 installer
    export PATH="/home/dchen/anaconda3/bin:$PATH"

However when Anaconda is installed, pacaur does not seem to be able to connect to the AUR.  I get the "Cannot connect to AUR" message when trying to search or install packages.

Commenting out this line, and restarting fixes the AUR problem.

Is there a way to fix this so the python from Anaconda can still be used?

**Comment by rmarquis** [comment] 2015-07-16 00:58
I am not sure what the issue is, but this seems not directly related to pacaur/cower.
The command above should only extend the current path with anoncanda path. Try to verify the actual value of $PATH is (before and after) and see if it show anything unusual.

**Comment by chendaniely** [comment] 2015-07-16 02:43
I'm not sure why adding that path to the beginning of path breaks, but I just removed it from my PATH and reinstalled everything and it works.  I don't see any python call in the pacaur file, so no idea why this breaks.  Perhaps there's a python module with the same name as something that is called from bash?

**Comment by chendaniely** [comment] 2015-07-16 02:44
I just reset everything and this is the current message:

    $ pacaur -Syyu
    :: Synchronizing package databases...
     core                                                  121.6 KiB  2.53M/s 00:00 [#############################################] 100%
     extra                                                1741.5 KiB  7.49M/s 00:00 [#############################################] 100%
     community                                               2.7 MiB  8.14M/s 00:00 [#############################################] 100%
     multilib                                              125.9 KiB  2.46M/s 00:00 [#############################################] 100%
    :: Starting full system upgrade...
     there is nothing to do
    :: Starting AUR upgrade...
     there is nothing to do
    $ . .bashrc
    $ pacaur -Syyu
    :: Synchronizing package databases...
     core                                                  121.6 KiB  2.97M/s 00:00 [#############################################] 100%
     extra                                                1741.5 KiB  7.00M/s 00:00 [#############################################] 100%
     community                                               2.7 MiB  7.88M/s 00:00 [#############################################] 100%
     multilib                                              125.9 KiB   620K/s 00:00 [#############################################] 100%
    :: Starting full system upgrade...
     there is nothing to do
    :: Starting AUR upgrade...
    parse error: unallowed token at this point in JSON text
                                            :: Could not connect to the AU
                         (right here) ------^

**Comment by rmarquis** [comment] 2015-07-16 08:42
According to yaourt reported issues, it seems anaconda provides its own version of curl and that one has troubles using https.

You can try removing anaconda's curl with ```conda remove curl```. Closing now.

**Closed by rmarquis** 2015-07-16 08:42 UTC
