### ISSUE TITLE
Colorization fails for AUR items

### ISSUE THREAD

**Issue by thx1111** [rmarquis/pacaur#540] opened 2016-08-22 15:28 UTC
pacaur 4.6.8-1

Searching with "pacaur -Ss", setting "--color=always" and piping output to "less", colorization fails for AUR items.  This happens even with "Color" set in /etc/pacman.conf, and there is no separate "Color" setting in /etc/xdg/pacaur/config.

Colorization should be consistent.

**Comment by rmarquis** [comment] 2016-08-22 15:49
Duplicate of #213. Patch welcome.

**Closed by rmarquis** 2016-08-22 15:49 UTC
