### ISSUE TITLE
Single search result causes exit code 1

### ISSUE THREAD

**Issue by d125q** [rmarquis/pacaur#584] opened 2016-10-15 20:27 UTC
Consider executing
```
pacaur -Ss pygmentize
```

`pacaur` displays the *one and only* search result correclty, but exits with code 1.  This does not happen if the search yields multiple results (e.g. `pacaur -Ss firefox`).

**Comment by rmarquis** [comment] 2016-10-15 21:29
Duplicate of #526. This issue is already fixed in master.

**Comment by d125q** [comment] 2016-10-15 22:08
It is not fixed.  I am running a build from the master branch, and the issue is present.

Also, it only happens when the single search result is from the official repositories; e.g. `pacaur -Ss rxvt-unicode-patched` displays the result and exists with status 0 correctly.

**Comment by rmarquis** [comment] 2016-10-15 22:09
Yes, can reproduce. Thx for the report.

**Comment by d125q** [comment] 2016-10-15 22:24
No problem.  I now see where the issue is (and it is not related to there being a single search result): the exit code returned is simply that of `cower -s -- pygmentize`, as it does not find anything that matches `pygmentize` in the AUR.

**Comment by rmarquis** [comment] 2016-10-16 12:16
Fixed in fc94a8eaabe809603d7e255eb9974fcbee885a8e.

It was a bit tricky to fix as we have to ensure the saved error code strings aren't empty (due to `--repo` and `--aur`). Might be possible to write it in a shorter way, but at least now it works.

**Closed by rmarquis** 2016-10-16 12:16 UTC
Labels: bug
