### ISSUE TITLE
pacaur showing false version of skipped package when installing one

### ISSUE THREAD

**Issue by drws** [rmarquis/pacaur#502] opened 2016-05-05 08:11 UTC
I think this output pretty much sums it up. The difference is that in the first case (without installing any package), the output version of the skipped package (gr-fosphor-git) is correct (e1eb11b-1), but when a package (android-bash-completion) is passed as a parameter for installation, the vesion of the skipped package is the same as the version of a third-party package (lostfiles 3.15-1) - the questionable line is marked in the output below.

    user@box: ~ pacaur -Syu --ignore "gr-fosphor-git"
    :: Synchronizing package databases...
     core is up to date
     extra is up to date
     community is up to date
    :: Starting full system upgrade...
     there is nothing to do
    :: Starting AUR upgrade...
    :: gr-fosphor-git: ignoring package upgrade (e1eb11b-1 => latest)
    :: resolving dependencies...
    :: looking for inter-conflicts...
    
    AUR Packages  (1):
    
    Name           Old Version  New Version
    
    aur/lostfiles  3.15-1       3.16-1                    
    
    :: Proceed with installation? [Y/n] n
    user@box: ~ pacaur -Syu --ignore "gr-fosphor-git" android-bash-completion
    :: Synchronizing package databases...
     core is up to date
     extra is up to date
     community is up to date
    :: Starting full system upgrade...
     there is nothing to do
    :: Package(s) android-bash-completion not found in repositories, trying AUR...
    :: Starting AUR upgrade...
    :: gr-fosphor-git: ignoring package upgrade (3.15-1 => latest) <<<<<<<<<<<<<<!
    :: resolving dependencies...
    :: looking for inter-conflicts...
    :: android-sdk-platform-tools-r23.1.0-2 has been flagged out of date on 2016-03-13
    
    AUR Packages  (3):
    
    Name                            Old Version  New Version
    
    aur/android-bash-completion                  20131016-1                
    aur/android-sdk-platform-tools               r23.1.0-2                 
    aur/lostfiles                   3.15-1       3.16-1                    
    
    :: Proceed with installation? [Y/n]

And after updating the non-relevant package (lostfiles), the output is still buggy:

    user@box: ~ pacaur -Syu --ignore "gr-fosphor-git" android-bash-completion
    :: Synchronizing package databases...
     core is up to date
     extra is up to date
     community is up to date
    :: Starting full system upgrade...
     there is nothing to do
    :: Package(s) android-bash-completion not found in repositories, trying AUR...
    :: Starting AUR upgrade...
    :: gr-fosphor-git: ignoring package upgrade ( => latest) <<<<<<<<<<<<<<!
    :: resolving dependencies...
    :: looking for inter-conflicts...
    :: android-sdk-platform-tools-r23.1.0-2 has been flagged out of date on 2016-03-13
    
    AUR Packages  (2):
    
    Name                            Old Version  New Version
    
    aur/android-bash-completion                  20131016-1                
    aur/android-sdk-platform-tools               r23.1.0-2                 
    
    :: Proceed with installation? [Y/n]

**Comment by rmarquis** [comment] 2016-05-05 08:18
Yep, something wrong here. Does the `gr-fosphor-git` package actually have an update? Its pkgver seems completely fancy.

**Comment by drws** [comment] 2016-05-05 09:05
Funny thing with gr-fosphor-git - it always wants to update, that's why I skip it. It is an experimental piece of software though, probably with buggy pkgver, but I think pacaur needs to be able to handle it nonetheless, that's why I reported it here - gr-fosphor-git's buggy package is another, separate issue imo.

**Comment by rmarquis** [comment] 2016-05-05 10:46
Should be fixed in 5a1fd1edafa66e6a77b0e01779b2066c0149717a. Would be great if you could confirm that the issue is indeed fixed.

**Comment by rmarquis** [comment] 2016-05-09 08:42
No response - I assume this is fixed. Please reopen if it isn't.

**Closed by rmarquis** 2016-05-09 08:42 UTC
Labels: bug
