### ISSUE TITLE
makedepends being skipped

### ISSUE THREAD

**Issue by justinnhli** [rmarquis/pacaur#321] opened 2015-03-20 16:32 UTC
I'm trying to install libtermkey-bzr, and which has extra/bzr as a makedepends. pacaur somehow skips installing bzr, causing the checkout of libtermkey to fail:

	$ pacaur -S libtermkey-bzr
	:: Package(s) libtermkey-bzr not found in repositories, trying AUR...
	:: resolving dependencies...
	:: looking for inter-conflicts...

	AUR Packages  (2):

	Name                Old Version  New Version

	aur/libtermkey-bzr               latest                    
	aur/unibilium                    1.1.2-1                   

	Repo Packages (1):

	Name                Old Version  New Version  Download Size

	extra/bzr                        2.6.0-1           4.93 MiB

	Repo Download Size:    4.93 MiB
	Repo Installed Size:  41.62 MiB

	:: Proceed with installation? [Y/n] 

	:: Retrieving package(s)...
	:: View libtermkey-bzr PKGBUILD? [Y/n] 

	:: libtermkey-bzr PKGBUILD viewed
	:: View unibilium PKGBUILD? [Y/n] n
	:: Checking unibilium integrity...
	==> Making package: unibilium 1.1.2-1 (Fri Mar 20 12:21:49 EDT 2015)
	==> WARNING: Skipping dependency checks.
	==> Retrieving sources...
	  -> Found v1.1.2.tar.gz
	==> Validating source files with md5sums...
		v1.1.2.tar.gz ... Passed
	==> Extracting sources...
	  -> Extracting v1.1.2.tar.gz with bsdtar
	==> Sources are ready.
	:: Checking libtermkey-bzr integrity...
	==> Making package: libtermkey-bzr 0.17.r12-2 (Fri Mar 20 12:21:49 EDT 2015)
	==> WARNING: Skipping dependency checks.
	==> Retrieving sources...
	  -> Branching http://bazaar.leonerd.org.uk/c/libtermkey/ ...
	/usr/bin/makepkg: line 468: bzr: command not found
	==> ERROR: Failure while branching http://bazaar.leonerd.org.uk/c/libtermkey/
		Aborting...
	:: failed to verify libtermkey-bzr integrity

Manually installing bzr allows libtermkey-bzr to be installed successfully. For reference, here's the PKGBUILD for libtermkey-bzr:

	# Maintainer: Florian Walch <florian+aur@fwalch.com>

	pkgname=libtermkey-bzr
	pkgver=0.17.r12
	pkgrel=2
	pkgdesc="Library for easy processing of keyboard entry from terminal-based programs."
	arch=('i686' 'x86_64')
	url="http://www.leonerd.org.uk/code/libtermkey"
	license=('MIT')
	depends=('unibilium')
	makedepends=('bzr')
	conflicts=('libtermkey')
	provides=("libtermkey=${pkgver}")
	source=("${pkgname}::bzr+http://bazaar.leonerd.org.uk/c/libtermkey/")
	sha256sums=('SKIP')

	pkgver() {
	  cd "${pkgname}"
	  bzr tags | sort -n -k3 | awk -v REV=$(bzr revno) 'END{ printf("%s.r%s\n",$2,REV-$3) }'
	}

	build() {
	  cd "${pkgname}"
	  make PREFIX=/usr termkey.h libtermkey.la
	}

	package() {
	  cd "${pkgname}"
	  make PREFIX=/usr DESTDIR="${pkgdir}" install
	  install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
	}

	# vim:set sw=2 sts=2 et:

**Comment by rmarquis** [comment] 2015-03-20 16:40
Are you sure you're using the very last version of pacaur? This area has had some rework done in latest releases.

**Comment by justinnhli** [comment] 2015-03-20 16:43
You're right - I was running on pacaur 4.2.20. My fault; closing the issue.

**Comment by justinnhli** [comment] 2015-03-20 17:02
Actually, I take that back. I updated pacaur and am still facing the same issue.

**Comment by justinnhli** [comment] 2015-03-20 17:04
Here's the output:

	[justinnhli@surnia ~]$ pacaur --version
	pacaur 4.2.22
	[justinnhli@surnia ~]$ pacaur -S libtermkey-bzr
	:: Package(s) libtermkey-bzr not found in repositories, trying AUR...
	:: resolving dependencies...
	:: looking for inter-conflicts...

	AUR Packages  (2):

	Name                Old Version  New Version

	aur/libtermkey-bzr               latest                    
	aur/unibilium                    1.1.2-1                   

	Repo Packages (1):

	Name                Old Version  New Version  Download Size

	extra/bzr                        2.6.0-1           0.00 MiB

	Repo Download Size:    0.00 MiB
	Repo Installed Size:  41.62 MiB

	:: Proceed with installation? [Y/n] 

	:: Retrieving package(s)...
	:: View libtermkey-bzr PKGBUILD? [Y/n] n
	:: View unibilium PKGBUILD? [Y/n] n
	:: Checking unibilium integrity...
	==> Making package: unibilium 1.1.2-1 (Fri Mar 20 13:03:19 EDT 2015)
	==> Retrieving sources...
	  -> Found v1.1.2.tar.gz
	==> Validating source files with md5sums...
		v1.1.2.tar.gz ... Passed
	:: Checking libtermkey-bzr integrity...
	==> Making package: libtermkey-bzr 0.17.r12-2 (Fri Mar 20 13:03:20 EDT 2015)
	==> Retrieving sources...
	  -> Branching http://bazaar.leonerd.org.uk/c/libtermkey/ ...
	/usr/bin/makepkg: line 468: bzr: command not found
	==> ERROR: Failure while branching http://bazaar.leonerd.org.uk/c/libtermkey/
		Aborting...
	:: failed to verify libtermkey-bzr integrity

**Comment by rmarquis** [comment] 2015-03-20 20:48
Thanks, I can reproduce. This is somewhat related to #317 and #313.

The first makepkg call in integrity check doesn't check for dependency because it produces an error for missing AUR packages, but it is required for VCS software. I'll need to add some extra code just to ensure the VCS clients are properly installed, by making use of the new VCSCLIENTS makepkg variable.

**Comment by rmarquis** [comment] 2015-03-22 09:14
Fixed in d9be03ad61f4cc3048f1a143b059557ecaa076f2.

**Closed by rmarquis** 2015-03-22 09:14 UTC
Labels: bug
