### ISSUE TITLE
Pacaur doesn't install makedepends before fetching sources for a package.

### ISSUE THREAD

**Issue by mikkeloscar** [rmarquis/pacaur#432] opened 2016-02-22 15:05 UTC
Hello. I use pacaur to install AUR packages in [arch-travis](https://github.com/mikkeloscar/arch-travis). A user has reported an issue (mikkeloscar/arch-travis#9) caused by pacaur not installing `bzr` (listed in the makedepends) before it tries to fetch sources for the package.

The package in question is [libunity](https://aur.archlinux.org/packages/libunity/) and you can replicate the problem if you don't have `bzr` installed on your system and run `pacaur -S libunity`.

Error log:

```
$ pacaur -S libunity
:: Package(s) libunity not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (3): dee-1.2.7-6  libdbusmenu-glib-12.10.3.15.04.20150410.2-2  libunity-7.1.4-2  
Repo Packages (1): bzr-2.7.0-1  

Repo Download Size:    0.00 MiB
Repo Installed Size:  41.98 MiB

:: Proceed with installation? [Y/n] 

:: Retrieving package(s)...
Cloning into 'libunity'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 5 (delta 0)
Unpacking objects: 100% (5/5), done.
Checking connectivity... done.
Cloning into 'dee'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 5 (delta 0)
Unpacking objects: 100% (5/5), done.
Checking connectivity... done.
Cloning into 'libdbusmenu'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 4 (delta 0)
Unpacking objects: 100% (4/4), done.
Checking connectivity... done.
:: View libunity PKGBUILD? [Y/n] n
:: View libunity.install script? [Y/n] n
:: View dee PKGBUILD? [Y/n] n
:: View libdbusmenu PKGBUILD? [Y/n] n
:: Checking libdbusmenu-glib integrity...
==> Making package: libdbusmenu 12.10.3.15.04.20150410.2-2 (Mon Feb 22 16:03:02 CET 2016)
==> Retrieving sources...
  -> Downloading libdbusmenu_12.10.3+15.04.20150410.2.orig.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2313k  100 2313k    0     0  2048k      0  0:00:01  0:00:01 --:--:-- 4773k
==> Validating source files with sha512sums...
    libdbusmenu_12.10.3+15.04.20150410.2.orig.tar.gz ... Passed
:: Checking dee integrity...
==> Making package: dee 1.2.7-6 (Mon Feb 22 16:03:04 CET 2016)
==> Retrieving sources...
  -> Downloading dee-1.2.7.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  695k  100  695k    0     0   888k      0 --:--:-- --:--:-- --:--:-- 2563k
==> Validating source files with sha256sums...
    dee-1.2.7.tar.gz ... Passed
:: Checking libunity integrity...
==> Making package: libunity 7.1.4-2 (Mon Feb 22 16:03:05 CET 2016)
==> Retrieving sources...
  -> Branching lp:libunity...
/usr/share/makepkg/source/bzr.sh: line 48: bzr: command not found
==> ERROR: Failure while branching lp:libunity
    Aborting...
:: failed to verify libunity integrity
```

**Comment by rmarquis** [comment] 2016-02-22 15:08
Yep, confirmed. Thought I had fixed that issue already, might be a regression due to the integrity check rework. Will have a deeper look asap.

**Comment by rmarquis** [comment] 2016-02-22 17:32
This is not a regression, but a specific situation that pacaur has never been able to handle properly. 

There is check to ensure VCS clients are installed before fetching the sources (commit of interest: d9be03ad61f4cc3048f1a143b059557ecaa076f2), but this works only for package that have a -git, -svn, -hg or -bzr extension.

However, the `libunity` PKGBUILD is a VCS package that fetches a specific commit, so its naming scheme is perfectly valid according to the [VCS packages guidelines](https://wiki.archlinux.org/index.php/VCS_package_guidelines). In addition, it is also a split package that has a `pkgbase` diifferent from all the `pkgname` of its subpackages.

Pacaur cannot retrieve the `MakeDeps` of that PKGBUILD through the RPC interface, as it  currently doesn't allow to lookup information of `pkgbase`, only `pkgname`. Parsing the `.SRCINFO` file and comparing with the defined `VCSCLIENTS`might be the only way to fix that issue.

**Comment by rmarquis** [comment] 2016-02-22 19:19
Fixed in b851f2820b1761a65567f42d2af3808c15c3189c.

**Closed by rmarquis** 2016-02-22 19:19 UTC
Labels: bug

**Comment by mikkeloscar** [comment] 2016-02-22 20:45
Thanks for the quick fix and all the info.

> In addition, split packages that have a pkgbase diifferent from all the pkgname of its subpackages and using a specific VCS commit prevent retrieval of the MakeDeps of that PKGBUILD through the RPC interface, as it currently doesn't allow to lookup information of pkgbase, only pkgname.

Can't you just grab the `pkgname`s from `.SRCINFO` in that case, and make the RPC with those?

**Comment by rmarquis** [comment] 2016-02-22 21:08
This is additional complexity, since it would require one more RPC call for an info that I can find in the already downloaded .SRCINFO file.
