### ISSUE TITLE
"Proceed with installation? [Y/n]" wants K or E instead.

### ISSUE THREAD

**Issue by Mikaela** [rmarquis/pacaur#436] opened 2016-03-06 11:33 UTC
I use Arch in Finnish and when I installed pacaur, I was confused on why it just quit when I answered `y` or `n`. Then I tried `k` and the installation continued and later `e` so it was aborted.

K is Kyllä (Yes in Finnish) and E is Ei (No in Finnish).

I think pacaur should either accept Y/n as input or ask for what it really wants.
- pacaur 4.5.4-1 installed from the AUR
- Arch Linux

**Comment by Yoshi2889** [comment] 2016-03-06 11:34
The same bug happens with Dutch, where it wants J instead of Y (Ja is Yes in Dutch).

**Comment by rmarquis** [comment] 2016-03-06 11:48
This is a translation issue, related to pacman being translated while pacaur doesn't have support for these languages yet. As translations are purely community made, I won't spend time on that issue.

Someone should send a translation (see howto in `po` directory), the alternative being that I remove translation support completely.

**Comment by Yoshi2889** [comment] 2016-03-06 11:49
I'm currently working on a Dutch translation. :)

**Comment by rmarquis** [comment] 2016-03-06 11:50
Great, I'm looking forward to it!

**Comment by Mikaela** [comment] 2016-03-06 13:13
Workaround: create alias which sets `LANG=en` before running pacaur.

In case someone is interested in doing Finnish translation, I [started one](https://github.com/Mikaela/pacaur/blob/l10n-fi/po/fi.po) but I am not comfortable with my translations and the messages are more understandable in English anyway.

**Comment by DoctorJellyface** [comment] 2016-04-24 06:33
You can just translate the [Y/n] part to get rid of this bug if you're not comfortable translating the rest.

**Comment by 14mRh4X0r** [comment] 2017-01-15 20:18
Would it be an option to check for the existence of a translation before using `gettext` to get the key names?

**Comment by rmarquis** [comment] 2017-01-15 20:35
No, because this translated string is passed to pacman during the install/update operations.

**Comment by durazell** [comment] 2017-01-20 16:19
Based on Mikaela's translation here is more complete: https://gist.github.com/durazell/2a218f960b3aaeca933c3112920066ef. I think it would be better to add global y/n support, yaourt supported both y/n and k/e which was more logical (many programs do this).

**Comment by rmarquis** [comment] 2017-01-20 16:23
Patch welcome.

**Comment by juergenhoetzel** [comment] 2017-05-02 16:36
> You can just translate the [Y/n] part to get rid of this bug if you're not comfortable translating the rest.

The root cause of this issue is the use of different text domains for the prompt (`pacaur`) and  input-check (`pacman`), which is wrong IMO. See my  [Pull Request](https://github.com/rmarquis/pacaur/pull/686)

**Comment by rmarquis** [comment] 2017-05-02 17:43
Fixed in 817d2f9affd3a880f92202f9723722746e5662bb.

**Closed by rmarquis** 2017-05-02 17:43 UTC
Labels: community
