### ISSUE TITLE
Problem with installing new packages from AUR

### ISSUE THREAD

**Issue by dw72** [rmarquis/pacaur#544] opened 2016-08-25 08:32 UTC
From some time I have problem with installing packages from AUR with pacaur

>~ > pacaur -Ss california
aur/california 0.4.0-2 (68, 1,60)
    A new calendar application for GNOME 3. It is currently under heavy development.
aur/blockout2 2.5-3 (30, 0,00)
    3D tetris, free adaptation of the original BlockOut DOS game edited by California Dreams in 1989
aur/california-git 0.3.0.r17.g555974b-1 (2, 0,00)
    A new calendar application for GNOME 3. It is currently under heavy development.
aur/ucdavisthesis 1.3-2 (2, 0,00)
    A University of California at Davis Thesis/Dissertation LaTeX Class

>~ > pacaur -S california
błąd:  pakiet california nie został znaleziony
:: Nie znaleziono znaleziony w repozytoriach; szukam w AUR...
 nie ma nic do zrobienia

Last messages are in polish and it means that california package is not found in repositories then pacaur search it in AUR but then claim there is nothing to do.

**Comment by rmarquis** [comment] 2016-08-25 08:42
Please follow [Bug-reports](https://github.com/rmarquis/pacaur/wiki/Bug-reports) and ensure your output in set to English.

**Comment by dw72** [comment] 2016-08-25 13:13
I think this is related to locale settings because when I set english locale the problem is gone.

**Comment by dw72** [comment] 2016-08-25 15:41
It is weird but when I unset LC_ALL variable and only LANG=pl_PL.utf8 is defined pacaur works with polish language

**Comment by rmarquis** [comment] 2016-08-25 18:28
Looks like #302.

**Comment by rmarquis** [comment] 2016-08-27 19:13
Can you confirm that the issue is the very same as #302?

**Comment by dw72** [comment] 2016-08-29 06:19
It looks very similar but the message is different. Here is "there is nothing to do" but in #302 "no results found for "found"... but maybe reason is the same

**Comment by rmarquis** [comment] 2016-08-29 23:24
That's not helping. Please post a debug output.

**Comment by dw72** [comment] 2016-08-30 06:27
No problem below is log, but messages is in polish... the problem occurs only when I set LC_ALL=pl_PL.utf8... if I have only LANG set to polish pacaur work ok in polish language too...

```
+ version=4.6.8
+ unset aur cleancache devel edit info installpkg foreign needed noconfirm nodeps noedit
+ unset operation pac pacQ pacS quiet rebuild refresh repo search selective upgrade
+ LC_COLLATE=C
+ TEXTDOMAIN=pacaur
+ TEXTDOMAINDIR=/usr/share/locale
+ [[ -n '' ]]
+ configdir=/etc/xdg/pacaur
+ userconfigdir=/home/milley/.config/pacaur
+ userpacmandir=/home/milley/.config/pacman
+ usercachedir=/home/milley/.cache/pacaur
+ [[ -r '' ]]
+ source /etc/makepkg.conf
++ DLAGENTS=('ftp::/usr/bin/curl -fC - --ftp-pasv --retry 3 --retry-delay 3 -o %o %u' 'http::/usr/bin/curl -fLC - --retry 3 --retry-delay 3 -o %o %u' 'https::/usr/bin/curl -fLC - --retry 3 --retry-delay 3 -o %o %u' 'rsync::/usr/bin/rsync --no-motd -z %u %o' 'scp::/usr/bin/scp -C %u %o')
++ VCSCLIENTS=('bzr::bzr' 'git::git' 'hg::mercurial' 'svn::subversion')
++ CARCH=x86_64
++ CHOST=x86_64-unknown-linux-gnu
++ CPPFLAGS=-D_FORTIFY_SOURCE=2
++ CFLAGS='-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong'
++ CXXFLAGS='-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong'
++ LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro
++ MAKEFLAGS=-j2
++ DEBUG_CFLAGS='-g -fvar-tracking-assignments'
++ DEBUG_CXXFLAGS='-g -fvar-tracking-assignments'
++ BUILDENV=(!distcc color !ccache check !sign)
++ OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !optipng !upx !debug)
++ INTEGRITY_CHECK=(md5)
++ STRIP_BINARIES=--strip-all
++ STRIP_SHARED=--strip-unneeded
++ STRIP_STATIC=--strip-debug
++ MAN_DIRS=({usr{,/local}{,/share},opt/*}/{man,info})
++ DOC_DIRS=(usr/{,local/}{,share/}{doc,gtk-doc} opt/*/{doc,gtk-doc})
++ PURGE_TARGETS=(usr/{,share}/info/dir .packlist *.pod)
++ COMPRESSGZ=(gzip -c -f -n)
++ COMPRESSBZ2=(bzip2 -c -f)
++ COMPRESSXZ=(xz -c -z - --threads=0)
++ COMPRESSLRZ=(lrzip -q)
++ COMPRESSLZO=(lzop -q)
++ COMPRESSZ=(compress -c -f)
++ PKGEXT=.pkg.tar.xz
++ SRCEXT=.src.tar.gz
+ [[ -r /home/milley/.config/pacman/makepkg.conf ]]
+ [[ -r /home/milley/.makepkg.conf ]]
+ tmpdir=/tmp/pacaurtmp-milley
+ clonedir=/home/milley/.cache/pacaur
+ editor=vi
+ displaybuildfiles=diff
+ fallback=true
+ silent=false
+ sortby=popularity
+ sortorder=descending
+ sudoloop=true
+ pacmanbin=pacman
+ aururl=aur.archlinux.org
+ aurrpc='/rpc.php?type=info&v=5'
+ source /etc/xdg/pacaur/config
+ [[ -r /home/milley/.config/pacaur/config ]]
+ [[ ! -d /tmp/pacaurtmp-milley ]]
+ [[ ! -d /home/milley/.cache/pacaur ]]
+ trap Cancel INT
+ args=($@)
+ for i in '"${args[@]}"'
+ [[ -S =~ ^-[a-zA-Z0-9] ]]
+ opts+=($i)
+ for i in '"${args[@]}"'
+ [[ california =~ ^-[a-zA-Z0-9] ]]
+ count=0
+ [[ -n -S ]]
+ getopts sidmykufecqrahvxVDFQRSTUbglnoptw-: OPT
+ pacmanarg+=("-$OPT")
+ case "$OPT" in
+ pacS=1
+ operation=sync
+ [[ -S =~ w ]]
+ installpkg=true
+ [[ -S =~ g ]]
+ [[ -S =~ l ]]
+ [[ -S =~ p ]]
+ getopts sidmykufecqrahvxVDFQRSTUbglnoptw-: OPT
+ [[ -z california ]]
+ pkgs+=("${!OPTIND}")
+ shift 2
+ OPTIND=1
+ [[ -n '' ]]
++ grep '^Color' /etc/pacman.conf
+ [[ -n Color ]]
+ [[ '' != \n\e\v\e\r ]]
+ [[ '' = \a\l\w\a\y\s ]]
+ coweropts+=("--color=auto")
+ reset='\e[0m'
+ colorR='\e[1;31m'
+ colorG='\e[1;32m'
+ colorY='\e[1;33m'
+ colorB='\e[1;34m'
+ colorM='\e[1;35m'
+ colorW='\e[1;39m'
+ pacmanarg=(${pacmanarg[@]/--/})
+ pacmanarg=(${pacmanarg[@]/-r/})
+ pacmanarg=(${pacmanarg[@]/-a/})
+ [[ sync = sync ]]
+ [[ ! -n '' ]]
+ [[ ! -n '' ]]
+ [[ ! -n '' ]]
+ [[ 1000 -eq 0 ]]
+ [[ -n 1 ]]
+ pacmanarg=(${pacmanarg[@]/-e/})
+ [[ -n 1 ]]
+ [[ -n '' ]]
+ [[ -n 1 ]]
+ [[ -n '' ]]
+ [[ ! -n vi ]]
+ [[ sync = sync ]]
+ [[ ! -n '' ]]
+ [[ ! -n '' ]]
+ [[ ! -n '' ]]
+ [[ diff = diff ]]
+ [[ /home/milley/.cache/pacaur = /tmp/pacaurtmp-milley ]]
+ [[ ! -w /home/milley/.cache/pacaur ]]
+ [[ -z california ]]
+ [[ -z california ]]
+ [[ -n '' ]]
+ case $operation in
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -z california ]]
+ ClassifyPkgs california
+ local noaurpkgs norepopkgs
+ [[ true = true ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ ! -n '' ]]
+ [[ ! -n '' ]]
+ unset noaurpkgs
+ for i in '"${pkgs[@]}"'
+ [[ california == aur/* ]]
+ noaurpkgs+=($i)
+ [[ -n california ]]
+ norepopkgs=($(LANG=C $pacmanbin -Sp ${noaurpkgs[@]} 2>&1 >/dev/null | awk '{print $NF}'))
++ LANG=C
++ pacman -Sp california
++ awk '{print $NF}'
+ for i in '"${norepopkgs[@]}"'
+ [[ !  california  =~ [a-zA-Z0-9.+-]+/znaleziony[^a-zA-Z0-9.+-] ]]
+ aurpkgs+=($i)
+ repopkgs=($(grep -xvf <(printf '%s\n' "${aurpkgs[@]}") <(printf '%s\n' "${noaurpkgs[@]}")))
+++ printf '%s\n' znaleziony
++ grep -xvf /dev/fd/63 /dev/fd/62
+++ printf '%s\n' california
+ [[ -n california ]]
+ sudo pacman -S california
[1;31mbłąd:  [0mpakiet california nie został znaleziony
+ [[ -n znaleziony ]]
+ [[ -n '' ]]
+ [[ true = true ]]
+ [[ ! -n '' ]]
+ Note w 'Nie znaleziono \e[1;39mznaleziony\e[0m w repozytoriach; szukam w \e[1;35mAUR\e[0m...'
+ case "$1" in
+ echo -e '\e[1;33m::\e[0m Nie znaleziono \e[1;39mznaleziony\e[0m w repozytoriach; szukam w \e[1;35mAUR\e[0m...'
+ Core znaleziony
+ GetIgnoredPkgs
+ ignoredpkgs+=($(grep '^IgnorePkg' '/etc/pacman.conf' | awk -F '=' '{print $NF}' | tr -d "'\""))
++ grep '^IgnorePkg' /etc/pacman.conf
++ awk -F = '{print $NF}'
++ tr -d ''\''"'
+ [[ -e /home/milley/.config/cower/config ]]
+ ignoredpkgs=(${ignoredpkgs[@]//,/ })
+ [[ -n '' ]]
+ IgnoreChecks
+ local checkaurpkgs checkaurpkgsAver checkaurpkgsQver i
+ [[ -z packettracer ]]
++ DownloadJson znaleziony
++ local urlencodedpkgs urlargs
++ urlencodedpkgs=($(sed 's/+/%2b/g;s/@/%40/g' <<< $@))
+++ sed 's/+/%2b/g;s/@/%40/g'
+++ printf '&arg[]=%s' znaleziony
++ urlargs='&arg[]=znaleziony'
++ [[ 17 -lt 8125 ]]
++ curl -sfg --compressed -C 0 'https://aur.archlinux.org/rpc.php?type=info&v=5&arg[]=znaleziony'
+ json='{"version":5,"type":"multiinfo","resultcount":0,"results":[]}'
+ unset aurpkgs
+ checkaurpkgs=($(GetJson "var" "$json" "Name"))
++ GetJson var '{"version":5,"type":"multiinfo","resultcount":0,"results":[]}' Name
++ json_verify -q
++ case "$1" in
++ json_reformat
++ tr -d '", '
++ awk -F '#' '{print $2}'
++ grep -Po 'Name:.*'
++ sed -r s/Name:/Name#/g
+ checkaurpkgsAver=($(GetJson "var" "$json" "Version"))
++ GetJson var '{"version":5,"type":"multiinfo","resultcount":0,"results":[]}' Version
++ json_verify -q
++ case "$1" in
++ json_reformat
++ tr -d '", '
++ grep -Po 'Version:.*'
++ awk -F '#' '{print $2}'
++ sed -r s/Version:/Version#/g
+ checkaurpkgsQver=($(expac -Q '%v' "${checkaurpkgs[@]}"))
++ expac -Q %v
+ NothingToDo
+ [[ -z '' ]]
+ printf '%s\n' ' nie ma nic do zrobienia'
+ exit
```

**Comment by rmarquis** [comment] 2016-08-30 07:50
Well, LC_ALL shouldn't normally be used, so I'll close this ticket as invalid. See https://wiki.archlinux.org/index.php/Locale#LC_ALL:_troubleshooting.

**Closed by rmarquis** 2016-08-30 07:50 UTC

**Comment by dw72** [comment] 2016-08-30 08:16
For clarity... the same situation is when I set LC_MESSAGES. When I set LC_NUMERIC, LC_TIME and other locale variables works ok.
