### ISSUE TITLE
If /var/lib/pacman/db.lck exists (read pacman is being used elsewhere) pacaur should wait for it to be removed rather than quitting

### ISSUE THREAD

**Issue by crossroads1112** [rmarquis/pacaur#300] opened 2015-01-09 00:22 UTC
Expected behavior:
As title says, if pacman is being used elsewhere, pacaur should wait instead of immediately quitting as yaourt does. 

Current behavior
makepkg tries to run pacman -U which throws an error and pacaur quits

Version:
4.2.17

**Comment by rmarquis** [comment] 2015-02-13 10:40
I am unsure about how to implement this. Pacaur installs built packages through `makepkg -i`, which throw the error away and stops when pacman is already in use:

```
error: failed to init transaction (unable to lock database)
error: could not lock database: File exists
  if you're sure a package manager is not already
  running, you can remove /var/lib/pacman/db.lck
==> WARNING: Failed to install built package(s).
```

The best I could do is waiting for pacman to be available before _starting_ the build, but that sounds completely silly, especially for long build. Since I'm not going away from `makepkg -i` for technical reasons, does someone has a suggestion here?

**Comment by Wildefyr** [comment] 2015-02-14 06:10
I'm no expert in programming, but couldn't you check in some way (dirty hack) if pacman was currently locked out? Then just recheck it every so often (i.e 1 minute), then throw a signal out to the window manager when it is free to start building so the user is informed the build is starting. Implement this with a flag as well, so people who want this functionality can use it while people who want the current behaviour are also happy.

**Comment by rmarquis** [comment] 2015-02-14 08:37
Checking if pacman is being used is easy (check for `/var/lib/pacman/db.lck `). This issue is that `makpkg` does the same, and refuse to start building if pacman is currently being used, thus preventing any build operation even if it doesn't require pacman right now.

In other word, this would require a patch to makepkg.

**Comment by crossroads1112** [comment] 2015-02-14 20:09
How does yaourt do this then?

**Comment by rmarquis** [comment] 2015-02-14 20:22
Yaourt doesn't use the `-i` flag of makepkg and does its own install soup (same for packer).
Not using the `-i` flag requires code duplication, and is very error prone especially with split packages. Technically, this is an absolute no go from my side.

**Comment by rmarquis** [comment] 2015-02-16 22:46
Since I don't see a way to implement this without impeding reliability, let's close this issue now.
Please add a makepkg feature request upstream, or better, send them a patch.

**Comment by vith** [comment] 2016-06-29 14:44
Just ran into this, probably because I have GNOME Software Center installed.

pacaur uses `pacman -U` now instead of `makepkg -i`, right? Something like this might be nice:

1. wait for the lock to be free
2. don't lock it yourself
3. run `pacman -U`
4. repeat if failure was caused by the pacman lock

It'll need retrying logic because of a TOCTOU race since we can't acquire the lock and give it away to pacman afaik. Unfortunately pacman won't make it easy to detect the failure reason as it seems to use exit code `1` for all errors.

**Comment by rmarquis** [comment] 2016-06-29 18:53
Yes, it does use `pacman -U` now.

However, I am not sure that implementing this would be a good idea. There are no way to check if the lock is only temporary, or if it exists for some reason (like a pacman crash). In that case, pacaur would hang and wait forever.

**Comment by vith** [comment] 2016-06-29 19:01
A message to the effect of "Waiting for /var/lib/pacman/db.lck to be removed, press ^C to cancel" should cover that I think.

**Comment by vith** [comment] 2016-06-29 19:17
Well I thought of one way to be able to acquire the lock and lend it to pacman... run pacman in a chrooted overlayfs of `/` where the only difference is that the lockfile doesn't exist.

Sounds super sketchy though.

**Comment by rmarquis** [comment] 2016-06-29 23:25
Way too sketchy, yes. I'll have a look when I can, but I am still not convinced this is worth it.

**Comment by rmarquis** [comment] 2016-09-27 09:35
Not worth it.

**Closed by rmarquis** 2016-09-27 09:35 UTC
Labels: feature
