### ISSUE TITLE
“Unresolved dependency” not helpful

### ISSUE THREAD

**Issue by flying-sheep** [rmarquis/pacaur#615] opened 2017-01-10 09:02 UTC
```console
$ pacaur -v
pacaur 4.6.10
```

Related to #36. When I ignore a package, pacaur doesn’t tell me why it wants to install it.

I’d like to know what package suddenly requires one of my blacklisted packages.

```console
$ LC_ALL=C pacaur -Sua
:: Starting AUR upgrade...
:: resolving dependencies...
:: kdelibs: ignoring package upgrade
:: Unresolved dependency 'kdelibs'
```

**Comment by rmarquis** [comment] 2017-01-10 10:29
Duplicate of #173.

**Closed by rmarquis** 2017-01-10 10:29 UTC
