### ISSUE TITLE
Missing transitive dependencies are hard to track down

### ISSUE THREAD

**Issue by hobarrera** [rmarquis/pacaur#602] opened 2016-12-02 23:12 UTC
###### Important

Read me first: [Bug reports](https://github.com/rmarquis/pacaur/wiki/Bug-reports)

###### Version

```
$ pacaur -v
pacaur 4.6.10
```
###### Description

Trying to run `pacaur -Syu` results in an error: `no results found for lib32-sqlite3`.  

Now, it's clear that this isn't pacaur's fault, some PKGFILE file refers to this package. However, it's very hard to find out which one; it's not installed locally, and no local package seems to depend on it.

To find out who's at fault, I had to run `pacaur -k` (which yielded about 20 results), and the recursively go through the dependencies until something failed (it was a second-level dependency in this case).

IMHO, pacaur should hint which PKGBUILD is the offending one, with something like:

    no results found for lib32-sqlite3 (required by lib32-python2)
    lib32-python2 failed (required by lib32-libwbclient)
    [etc]

**Comment by rmarquis** [comment] 2016-12-03 13:11
Duplicate of #173.

**Closed by rmarquis** 2016-12-03 13:11 UTC
