### ISSUE TITLE
Pacaur fails with SRCINFO/PKGBUILD mismatch

### ISSUE THREAD

**Issue by sandler31** [rmarquis/pacaur#567] opened 2016-10-03 14:02 UTC
Command I use for install:
`$ pacaur -S google-breakpad-git`

```
...
==> Leaving fakeroot environment.
==> Finished making: google-breakpad-git r1540.98b6a63-1 (Mon Oct  3 16:43:45 IDT 2016)
==> Cleaning up...
:: Installing google-breakpad-git package(s)...
:: google-breakpad-git package(s) failed to install. Check .SRCINFO for mismatching data with PKGBUILD.
```

When I install manually eveyhting works fine:
```
$ git clone https://aur.archlinux.org/google-breakpad-git.git
$ cd google-breakpad-git
$ makepkg -sri
```

```
...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "google-breakpad-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: google-breakpad-git r1540.98b6a63-1 (Mon Oct  3 16:53:11 IDT 2016)
==> Installing package google-breakpad-git with pacman -U...
[sudo] password for mich: 
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) google-breakpad-git-r1540.98b6a63-1

Total Installed Size:  5.65 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                        [#######################################] 100%
(1/1) checking package integrity                                      [#######################################] 100%
(1/1) loading package files                                           [#######################################] 100%
(1/1) checking for file conflicts                                     [#######################################] 100%
(1/1) checking available disk space                                   [#######################################] 100%
:: Processing package changes...
(1/1) installing google-breakpad-git                                  [#######################################] 100%
```

I've found an issue here with a similar description, but it seems the cause was different, as the issue was closed due to a fix. (#414)

**Comment by rmarquis** [comment] 2016-10-03 14:07
Duplicate of #564.

**Closed by rmarquis** 2016-10-03 14:07 UTC

**Comment by sandler31** [comment] 2016-10-03 14:09
Sorry for that :(
Missed this one
