### ISSUE TITLE
option to abort installation when a package fails to build

### ISSUE THREAD

**Issue by v01d** [rmarquis/pacaur#520] opened 2016-06-25 00:59 UTC
When building a group of packages on AUR, if a package fails to build, installation continues to attempt to build other packages. When building a lot of packages, it is difficult to find where the failed build/s raised errors while compiling and sometimes the error can get lost in scrollback history. It would be nice to support an option to fail the whole installation as soon as a package fails to build (kind of like the set -e option of bash).

**Comment by rmarquis** [comment] 2016-06-25 09:39
This should already be implemented. In fact, people usually ask me to implement the opposite behavior (continuing the build even if one package fails) which I refuse to do. Please provide a debug output.

**Comment by ixjlyons** [comment] 2016-06-25 18:04
I think the issue is that it would be nice to be able to inspect the build output when a build fails. This output is lost unless it happens to be one of the last packages to build and/or you have a huge scrollback buffer.

Once the update finishes and you see that a package failed to build, you can just navigate to the build directory and `makepkg` or run `pacaur -u failedpackage`, but for an error occurring late in a long build, this isn't ideal. The `--silent` option is a good way to handle it, but then you miss out on the mesmerizing cascade of gcc output :)

**Comment by rmarquis** [comment] 2016-06-25 18:33
So in a nutshell, the real issue is that users don't increase their buffer output. Stopping the build when failing would only be an inappropriate workaround for something easy to configure.

Sounds like a "wontfix" to me.

**Comment by v01d** [comment] 2016-06-25 20:37
It is not a (only) matter of insufficient scrollback buffer. Even if you
save everything, finding the error is non-trivial. If you look for "error"
it matches the output of all packages which try to build and quickly fail
since the dependencies are unmet, due to the previous failed builds. So
finding the compilation error of the corresponding package becomes quite
difficult.

For example, (my usual use case) doing a pacaur -S ros-indigo-desktop-full
with an intermediate package failing is quite troublesome.

**Comment by rmarquis** [comment] 2016-06-26 11:49
And what prevents you to look for the first error occurrences then? I hardly see how this isn't strictly a buffer output issue, and thus this is a wontfix from my side.

**Closed by rmarquis** 2016-06-26 11:49 UTC
