### ISSUE TITLE
pacaur detects upgrades from AUR even though they are up to date

### ISSUE THREAD

**Issue by imranmunshi** [rmarquis/pacaur#475] opened 2016-04-07 07:58 UTC
When installing from pacaur, it shows many AUR packages that are installed as not installed due to which it always keeps showing upgrades for those packages. Attached is a debug log from `pacaur -Sa rar`
[pacaur-dbg.txt](https://github.com/rmarquis/pacaur/files/207933/pacaur-dbg.txt)

**Comment by rmarquis** [comment] 2016-04-07 11:48
Your debug output only shows that you're trying to install the rar package while it is in cache. I don't see anything related to upgrade here.

Can you post a regular output where the issue is clearly visible?

**Comment by imran27** [comment] 2016-04-07 12:08
[pacaur-syu-dbg.txt](https://github.com/rmarquis/pacaur/files/208312/pacaur-syu-dbg.txt)

**Comment by rmarquis** [comment] 2016-04-07 12:20
See that "downloading community.db..." line that is repeated 50 times or so? The community db is not updated correctly, and pacaur is not designed to work on a broken system.  Find out what's wrong with your system, and fix it. This is not a pacaur issue.

**Comment by imran27** [comment] 2016-04-07 12:39
The issue however is not related to core repositories, it related to AUR which is managed by pacaur

**Comment by rmarquis** [comment] 2016-04-07 12:42
If the core repositories aren't updated as expected, of course the foreign packages detection, and pacaur by extension, will have erratic behavior.

**Comment by imran27** [comment] 2016-04-07 12:46
After sudo pacman -Syyu the community.db is fixed, yet now pacaur is showing upgrades!
[pacaur-syu-dbg.txt](https://github.com/rmarquis/pacaur/files/208383/pacaur-syu-dbg.txt)

**Comment by imran27** [comment] 2016-04-07 12:48
Can you please reopen and look into this issue? Please do tell me if you need any more information or want me to try some more things.

**Comment by rmarquis** [comment] 2016-04-07 12:53
Please start to check pacaur/cower/expac version. Since you are using -git releases, you might not have the latest versions. If the issue still occurs, try the respective stable releases.
If the issue still occurs, check the foreign package list (pacman -Qm) and pacaur -Qua output.

**Comment by imran27** [comment] 2016-04-07 13:18
Installed the latest git versions of all the 3 mentioned packages ({expac,cower,pacaur}-git), issue still persists. pacaur -Qm shows package versions properly while pacaur -Qua shows upgrades to all but a few of those foreign packages and the local package versions of those available upgrades are empty values!

**Comment by imran27** [comment] 2016-04-07 13:20
The latest build from git version has issues, the stable version works fine

**Comment by rmarquis** [comment] 2016-04-07 13:26
Try again with pacaur-git, but stable cower and expac.

I can't reproduce your issue with latest git version of all three. Your issue seems related to an outdated expac.

**Comment by imran27** [comment] 2016-04-07 13:43
cower : stable & expac,pacaur-git :: issue

expac : stable & cower,pacaur-git :: issue

<table style="width:100%">
    <tr>
        <td>cower</td>
        <td>expac</td>
        <td>pacaur</td>
        <td>Issue?</td>
    </tr>
    <tr>
        <td>stable</td>
        <td>stable</td>
        <td>git</td>
        <td>Yes</td>
    </tr>
    <tr>
        <td>stable</td>
        <td>git</td>
        <td>git</td>
        <td>Yes</td>
    </tr>
    <tr>
        <td>git</td>
        <td>stable</td>
        <td>git</td>
        <td>Yes</td>
    </tr>
    <tr>
        <td>git</td>
        <td>git</td>
        <td>stable</td>
        <td>No</td>
    </tr>
</table>

Do you need any more testing?

**Comment by rmarquis** [comment] 2016-04-07 14:01
I still can't reproduce the issue. For the next version, pacaur is moving from directly using cower to using expac and a RPC call, as commited in c9b3aa232deac58c7063b4ec414633dd57534c4d and b693df19e6c7705abf5e2a37305f085d2e597e3c. The involved code is the following (`-Qua` and `-Sua` are handled in a similar way):

```
    foreignpkgs=($($pacmanbin -Qmq))
    json=$(DownloadJson ${foreignpkgs[@]})
    aurpkgsAname=($(GetJson "var" "$json" "Name")) # return sorted results
    aurpkgsAver=($(GetJson "var" "$json" "Version"))
    aurpkgsQver=($(expac -Q '%v' ${aurpkgsAname[@]}))
    for i in "${!aurpkgsAname[@]}"; do
        [[ $(vercmp "${aurpkgsAver[$i]}" "${aurpkgsQver[$i]}") -gt 0 ]] && aurpkgsQood+=(${aurpkgsAname[$i]});
    done
```

It looks like the expac call returns an empty string, which make `vercmp` detect all package has being outdated.

Check the output of `expac -Q '%v' arduino`, or any other of your installed foreign package. If a version string isn't returned, please post the debug output of `pacaur -Qua`.

**Comment by imran27** [comment] 2016-04-07 14:08
You caught it right, `expac -Q '%v'` returns empty string for just about any package.
Attached is the log.
[pacaur-Qua.txt](https://github.com/rmarquis/pacaur/files/208526/pacaur-Qua.txt)

**Comment by rmarquis** [comment] 2016-04-07 14:14
Well, this should never happen. It is possible that your local database is corrupt. Check if pacman can actually find local packages with `pacman -Q, or `pacman -Q arduino`. If you get no output whatsoever, you might find the [following link](https://wiki.archlinux.org/index.php/Pacman/Restore_local_database) useful.

This might be related to the refresh of the community.db above. In any case, there is little I can do here since this is not related to pacaur. Good luck!

**Comment by imran27** [comment] 2016-04-07 14:17
pacman is able to find and identify arduino and its version.

expac doesn't work.

**Comment by rmarquis** [comment] 2016-04-07 14:23
One last tip that might or might not help you: Try `pacman -Dk` and `pacman -Dkk` to check databases integrity. If you still can't find the issue, I'd suggest to report the issue to the [expac maintainer](https://github.com/falconindy/expac).

**Comment by imran27** [comment] 2016-04-07 15:23
`pacman -Dk` and `pacman -Dkk` do not return anything (probably means that the databases are intact and healthy)

I would have to look into expac. This means that pacaur stable is not using expac extensivel?

**Comment by rmarquis** [comment] 2016-04-07 15:47
It does, but not for checking AUR update unlike pacaur-git. You're likely to run into other issues with the stable release.

**Comment by imran27** [comment] 2016-04-07 16:43
That was an issue of expac, reported it and it is fixed now. pacaur-git also works fine now

**Comment by rmarquis** [comment] 2016-04-07 17:11
That was indeed a weird bug. For reference, link to [upstream issue](https://github.com/falconindy/expac/issues/27).

**Closed** 2016-04-07 23:00 UTC
Labels: invalid
